title: "Kubernetes — Persistent Volumes"
description: "API for users and administrators that abstracts how storage is provided."
authors:
  - 'Kubernetes Authors'
created_at: 2026-04-26
updated_at: 2026-04-26
source: "https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/concepts/storage/persistent-volumes.md"
license: "CC BY 4.0"
tags:
  - 'kubernetes'
  - 'storage'
  - 'pv'
  - 'pvc'
language: en
category: "manuals/kubernetes"
